PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS teams(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS roster_entries(team_id INTEGER REFERENCES teams(id),name TEXT NOT NULL,source_url TEXT NOT NULL,PRIMARY KEY(team_id,name));
CREATE TABLE IF NOT EXISTS players(id TEXT PRIMARY KEY,name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS matches(id TEXT PRIMARY KEY,date TEXT NOT NULL,venue TEXT NOT NULL,team1 INTEGER REFERENCES teams(id),team2 INTEGER REFERENCES teams(id),winner INTEGER REFERENCES teams(id),result TEXT NOT NULL,toss TEXT,pom TEXT,dls INTEGER NOT NULL DEFAULT 0,warning TEXT,source_url TEXT NOT NULL,retrieved_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS innings(match_id TEXT REFERENCES matches(id) ON DELETE CASCADE,number INTEGER,team_id INTEGER REFERENCES teams(id),runs INTEGER NOT NULL,wickets INTEGER NOT NULL,balls INTEGER NOT NULL,extras INTEGER NOT NULL,PRIMARY KEY(match_id,number));
CREATE TABLE IF NOT EXISTS batting(match_id TEXT,innings_number INTEGER,player_id TEXT REFERENCES players(id),position INTEGER,runs INTEGER NOT NULL,balls INTEGER NOT NULL,fours INTEGER NOT NULL,sixes INTEGER NOT NULL,dismissal TEXT,not_out INTEGER NOT NULL,PRIMARY KEY(match_id,innings_number,player_id),FOREIGN KEY(match_id,innings_number) REFERENCES innings(match_id,number) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS bowling(match_id TEXT,innings_number INTEGER,player_id TEXT REFERENCES players(id),position INTEGER,balls INTEGER NOT NULL,runs INTEGER NOT NULL,wickets INTEGER NOT NULL,dots INTEGER NOT NULL,wides INTEGER NOT NULL,no_balls INTEGER NOT NULL,PRIMARY KEY(match_id,innings_number,player_id),FOREIGN KEY(match_id,innings_number) REFERENCES innings(match_id,number) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS notes(team_id INTEGER PRIMARY KEY REFERENCES teams(id),body TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS auth(id INTEGER PRIMARY KEY CHECK(id=1),salt TEXT NOT NULL,pin_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,csrf TEXT NOT NULL,expires REAL NOT NULL);
CREATE TABLE IF NOT EXISTS login_attempts(ip TEXT,time REAL);
CREATE TABLE IF NOT EXISTS import_log(id INTEGER PRIMARY KEY,imported_at TEXT NOT NULL,matches INTEGER NOT NULL,source TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_batting_player ON batting(player_id,match_id);
CREATE INDEX IF NOT EXISTS idx_bowling_player ON bowling(player_id,match_id);
CREATE INDEX IF NOT EXISTS idx_matches_date ON matches(date);
CREATE INDEX IF NOT EXISTS idx_innings_team ON innings(team_id,match_id);
CREATE INDEX IF NOT EXISTS idx_login_ip_time ON login_attempts(ip,time);
PRAGMA user_version=1;
